language: java
jdk:
  - oraclejdk7
branches:
  except:
    - /^build-[0-9a-z\-]*/


script: gradle awsPackage


deploy:
  provider: codedeploy
  access_key_id: AKIAJNDRC5LUHERE4YEQ
  secret_access_key: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
    secure: abhi0620
  bucket: 'technikfda.bucket.s3'
  deployment-group: 'technickFDADemoApplicationGroup'
  instance-group: 'technikfda:technikfda'

notifications:
  email:
  - technikfdacode@gmail.com