language: java
jdk:
- oraclejdk7
branches:
  except:
  - "/^build-[0-9a-z\\-]*/"
script: gradle awsPackage
deploy:
- provider: codedeploy
  access_key_id: AKIAIN4EOXPZMBUAO44Q
  secret_access_key: *1
  bucket: technikfda.bucket.s3
  key: latest/MyApp.zip
  bundle_type: zip
  application: technickFDADemoApplication
  deployment_group: technickFDADemoApplicationGroup
  on: *2
notifications:
  email:
  - technikfdacode@gmail.com