language: java
jdk:
- oraclejdk7
branches:
  except:
  - "/^build-[0-9a-z\\-]*/"
script: gradle awsPackage
notifications:
  email:
  - technikfdacode@gmail.com
deploy:
- provider: releases
  api_key:
    secure: GbETLby5i/ndyno7306i5r5qUKXITCYMWZ0vAc0n6d26Lqru1HvP7vIbairDyXBOYXEccUaiJQhJ9HZ8Ua6RLucKBjYhpl11aUgP/vxp8Oe9RQFc+cFYcDhZK+83dfCaGS4zwJvwZjs+Bmu1C/MFji4ZqKBRYliNtJ80xouUNUhsk8UBRuEFZR/biMgWv13Wh9DkboS5bbk4V2G/pIMsuwX1mVoXszOE6u+Su5NuTXxgQkjv1Q3M5T32qS9NrT/F9Lism2+lbegyht4RO4tlVGUCF6E+CKHn7/2jEcyUTYhPghE1t/2UjnxeREHEyykw6/6DpH2UfRJZ3NVEq72DRAWt0o0JUCI2CWc6mRA81N1GnEsiJM5UkXT9Mc8oNjSPQy8FCBJUeoe16AYLVP9j1zRlqH4JfWmuLYcHb534b24O7TEGmvpJmSGMSblQS8uICE1Fq8VPjRRbcEgjIkggC6CaI2If8UTLmiTAA/9ZTish3yU2zzQh38QHo4pYbm82QVrj2Y5HK3oMK/id9Hw3CNS3cQi7bJqNrDiInyVxqLvvb1Qmgqr8Ufauh/47vGov+TuI0YuD7cqCsaFGc4+TgQ0iERDGQBKRukqxYwmORtsEfE9ZPLSNzpVIbJx/BZ+g7G8NTRVq82+soKoUTEQ4pqttqMtYuzeAXPEzot1KYRA=
  file: technikfda.war
  on:
    repo: TechnikInc/openFDA-DevelopmentPrototype
    tags: true
    all_branches: true
- provider: s3
  access_key_id: AKIAIN4EOXPZMBUAO44Q
  secret_access_key: &1
    secure: VZM5ERH/TSL9A03eywkmwIownNc6sfllVkRTZEjWPhM8EuwyZoG2Me+DQpTPbwwHIm96EY69AES3D3XmNcgRr+c5wFrDqmVr0URVk04fWcEFFl2n2eDYq3J+ZQjshgY/LESXeIKa8LDNr437onG67WTVqIF4P2NF0OR27MALl7pYZONwJjtmzx/j8ipCdM7sc8kn2AzQEoTVjNSO9YEhqU5Fq8Huj/rEKG+FXzLh9e9HQUfxriClc3PgA0m4ZFJRKj2ZfzuDG15UsKEa1kPyE+tUV38HycdJwjKK8lvidD3wojQFDdVRHd0qMk4Rp19B2pk3bSUIxyk8RDUDV1QTx3aC5GGzD39O+pJDz4fwj998EvJ7vMH2OiwCsCxOdQjTLnB/NZMZQtBFPbhI8QBHdmHr7dgBgqJPD/nYsuDCjOjgWbmdPbue9FsqYcuh5x7dHD1pPBrKwP2/VxXeN3FrFrxWN+jYhQlEZ08EByj5Bk/EFkDiSNFJKb/UJjKhtf3/NASovOlqWpCc8D2Nv9tynNDxHMI7zscEkbd9QcgGs7L1gu1L27Y60n1O7ThT1EJ4nG/HRD/p6M2UhyoYUI7MWFMy+M8kCjiweIcbbE5pVkb/WlAduAJN2YItutHDZOj0We4pAqWC1xI+5CKT2iiouz9J9hZ+RW9Jir38FkUu69c=
  local_dir: build/distributions
  skip_cleanup: true
  on: &2
    repo: TechnikInc/openFDA-DevelopmentPrototype
  bucket: technikfda.bucket.s3
  upload_dir: latest
- provider: codedeploy
  access_key_id: AKIAIN4EOXPZMBUAO44Q
  secret_access_key: *1
  bucket: technikfda.bucket.s3
  key: latest/MyApp.zip
  bundle_type: zip
  application: MyApp
  deployment_group: MyDeploymentGroup
  on: *2
