version: 0.0
# AppSpec Configuration for AWS Code Deploy
os: linux 

# We need to copy our artifacts over to the tomcat applications directory, which is /usr/share/tomcat<Version>/webapps
# This can be replaced with an environment variable reference defined in the 
# AWS instance - for example 
# for this application technikfda.war is the only file we need to deploy
files:
  - source: technikfda.war
    destination: /usr/share/tomcat7/webapps

# Before the application is deployed, Tomcat needs to be stopped and 
# the existing applications cleaned up, otherwise, AWS Codedeploy will not
# overwrite the files. 
hooks:
 ApplicationStop:
   - location: tomcat_stop_clean.sh
# Now we can start up Tomcat once again
 ApplicationStart:
   - location: tomcat_start.sh